### ISSUE TITLE
[Bug] OPPO手机选择应用后点击开始性能采集后手机卡主然后自动重启

### ISSUE THREAD

**Issue by jeniva** [SonicCloudOrg/sonic-agent#404]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.3

### Deploy platform

Windows10

### Minimal reproduce step

手机型号，![image](https://github.com/SonicCloudOrg/sonic-agent/assets/8514029/8ebf220e-2d99-4a3f-8600-e352649d0e8d)
点击马上使用->性能检测->选择应用->开始监控，就卡着了，我看日志好像是权限拒绝了，我试了其他应用好像还好，这个是我们应用的问题吗，还是说要怎么开启权限才行
01-12 16:24:53.831 29808 29808 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 29808 (init), pid 29808 (init)
01-12 16:24:53.831 27100 27730 D AudioPolicyService: UidPolicy::onUidStateChanged() UID=10174 procState=20
01-12 16:24:53.855 27099 27099 D Zygote  : Forked child process 29815
01-12 16:24:53.863 29815 29815 E Zygote  : GL_OOM reserved vma failed, errno:22
01-12 16:24:53.867 27265 27568 I ActivityManager: Start proc 29815:com.oppo.multimedia.dirac/u0a174 for broadcast {com.oppo.multimedia.dirac/com.oppo.multimedia.dirac.service.BootCompletedReceiver}
01-12 16:24:53.869 29825 29825 F crash_dump64: crash_dump.cpp:465] failed to attach to thread 29808: Permission denied
01-12 16:24:53.870  1775  1775 I /system/bin/tombstoned: received crash request for pid 29808
01-12 16:24:53.871  1775  1775 W /system/bin/tombstoned: crash socket received short read of length 0 (expected 12)
01-12 16:24:53.872 29815 29815 E ultimedia.dira: Unknown bits set in runtime_flags: 0x20000
01-12 16:24:53.879 29808 29808 F libc    : crash_dump helper failed to exec
01-12 16:24:53.882 29815 29815 E ultimedia.dira: Not starting debugger since process cannot load the jdwp agent.
01-12 16:24:53.889 29818 29837 I adbd    : opening control endpoint /dev/usb-ffs/adb/ep0
01-12 16:24:53.890 29818 29837 I adbd    : UsbFfsConnection constructed
01-12 16:24:53.897 29819 29819 I /system/bin/phoenix_log_manager: [PHOENIX] prepare_bootlog: begin prepare boolog
01-12 16:24:53.900 29819 29819 I /system/bin/phoenix_log_manager: [PHOENIX] verify_magic: magic number verify success
01-12 16:24:53.900 29819 29819 I /system/bin/phoenix_log_manager: [PHOENIX] check_poweron_reason: no expected poweron reason
01-12 16:24:53.900 29819 29819 I /system/bin/phoenix_log_manager: [PHOENIX] prepare_bootlog: do not need save bootlog
01-12 16:24:53.912 27100 27730 D AudioPolicyService: UidPolicy::onUidStateChanged() UID=10174 procState=12
01-12 16:24:53.913 29815 29815 W System.err: java.io.FileNotFoundException: /data/logswitch/switch.xml: open failed: EACCES (Permission denied)
01-12 16:24:53.913 29815 29815 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:496)
01-12 16:24:53.913 29815 29815 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
01-12 16:24:53.913 29815 29815 W System.err: 	at java.io.FileReader.<init>(FileReader.java:72)
01-12 16:24:53.913 29815 29815 W System.err: 	at com.oppo.debug.InputLog.readString(InputLog.java:394)
01-12 16:24:53.913 29815 29815 W System.err: 	at com.oppo.debug.InputLog.getCurrentLogSwitchValue(InputLog.java:420)
01-12 16:24:53.913 29815 29815 W System.err: 	at com.oppo.debug.InputLog.startWatching(InputLog.java:126)
01-12 16:24:53.913 29815 29815 W System.err: 	at com.oppo.debug.InputLog.<clinit>(InputLog.java:77)
01-12 16:24:53.913 29815 29815 W System.err: 	at android.app.ActivityThread.attach(ActivityThread.java:7556)
01-12 16:24:53.913 29815 29815 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7785)
01-12 16:24:53.913 29815 29815 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 16:24:53.913 29815 29815 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
01-12 16:24:53.913 29815 29815 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
01-12 16:24:53.914 29815 29815 W System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
01-12 16:24:53.914 29815 29815 W System.err: 	at libcore.io.Linux.open(Native Method)
01-12 16:24:53.914 29815 29815 W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
01-12 16:24:53.914 29815 29815 W System.err: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
01-12 16:24:53.914 29815 29815 W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
01-12 16:24:53.914 29815 29815 W System.err: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7697)
01-12 16:24:53.914 29815 29815 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:482)
01-12 16:24:53.914 29815 29815 W System.err: 	... 11 more
01-12 16:24:53.914 29815 29815 D InputLog: readString failed 
01-12 16:24:53.914 29815 29815 W System.err: java.io.FileNotFoundException: /data/logswitch/switch.xml: open failed: EACCES (Permission denied)
![image](https://github.com/SonicCloudOrg/sonic-agent/assets/8514029/354d09e7-fb76-4760-b29e-dbcfcb3431bd)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by jeniva** [comment]
![image](https://github.com/SonicCloudOrg/sonic-agent/assets/8514029/339bcfb3-4bdf-4acb-8e29-a17ac35f50e1)
补充一下agent端的日志

**Comment by ZhouYixun** [comment]
> ![image](https://private-user-images.githubusercontent.com/8514029/296636624-339bcfb3-4bdf-4acb-8e29-a17ac35f50e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDEwMDUsIm5iZiI6MTcwNTMwMDcwNSwicGF0aCI6Ii84NTE0MDI5LzI5NjYzNjYyNC0zMzliY2ZiMy00YmRmLTRhY2ItOGUyOS1hMTdhYzM1ZjUwZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMDYzODI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2RhNmRmMzU1OTJjOWIzNTNmZjgzYmNiMmI0ZTJhOTdmYWZkMDIxYjgwYjJmZWRhZDc0ODkzZjE2NjcwMTE1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f-7D3p5vMiHX11m4ZGusOtDXgoAP68w6obeAYE_xGk4) 补充一下agent端的日志

关闭权限监控了吗？oppo的设置可以看下官网

**Comment by jeniva** [comment]
都设置了还是会卡主，一开启性能监控就卡主，过会就重启了
![image](https://github.com/SonicCloudOrg/sonic-agent/assets/8514029/1c0176e8-5665-4ee9-8da3-e293bcbdbf26)

**Comment by jeniva** [comment]
随便找了一个应用也卡主的
![image](https://github.com/SonicCloudOrg/sonic-agent/assets/8514029/5f0b6c70-57a4-4e7c-bb84-29f5351ca369)

**Comment by ZhouYixun** [comment]
> 随便找了一个应用也卡主的 ![image](https://private-user-images.githubusercontent.com/8514029/296908542-5f0b6c70-57a4-4e7c-bb84-29f5351ca369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzUyNTIsIm5iZiI6MTcwNTM3NDk1MiwicGF0aCI6Ii84NTE0MDI5LzI5NjkwODU0Mi01ZjBiNmM3MC01N2E0LTRlN2MtYmI4NC0yOWY1MzUxY2EzNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDMxNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2E4MGUzYWU0NzU1YTRmNmQ5MTY2YjFlYmYwODUwMTE0YWM5YmIxNGU4NDI5OGU0NjJjNDM4NTc2ODk1MzQ5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9a9DZ0vLZjauEeQO7-3xBMOKaZKXUDAwRwDuHcVwqJk)

为什么两个屏的，你是二开过？

**Comment by jeniva** [comment]
没有呢，我换成2.6.3就2个屏，我还以为你们的新功能，还想问下怎么关掉

**Comment by ZhouYixun** [comment]
> 没有呢，我换成2.6.3就2个屏，我还以为你们的新功能，还想问下怎么关掉

奇怪了，我们没改过这块。关于oppo问题还真不好整，我们测试过几款机型没出现这个问题

**Comment by jeniva** [comment]
> > 没有呢，我换成2.6.3就2个屏，我还以为你们的新功能，还想问下怎么关掉
> 
> 奇怪了，我们没改过这块。关于oppo问题还真不好整，我们测试过几款机型没出现这个问题

我这边接入所有手机都两个屏呢，然后Android的性能采集都比较卡，这是为啥呀
