### ISSUE TITLE
[Bug] Agent连接IOS手机启动Wda时报错

### ISSUE THREAD

**Issue by chenshuai12** [SonicCloudOrg/sonic-agent#413]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.3

### Deploy platform

Windows10

### Minimal reproduce step

IOS型号：iPhoneSE
版本：15.4

### 问题复现
本地调试时，点击网页端马上使用后，投屏一直显示准备图像中
![image](https://github.com/SonicCloudOrg/sonic-agent/assets/22972966/fa0ea7d5-4a85-4402-a79a-fd057a2da2d9)
![image](https://github.com/SonicCloudOrg/sonic-agent/assets/22972966/eaf9ed12-c83d-4845-bf71-209ead708e88)

查看日志，发现SibTool 启动Wda包时，报错了
2024-02-27 10:29:51.206 - INFO 21092 --- [http-nio-7777-exec-1] o.c.sonic.agent.websockets.IOSWSServer   : ios lock udId：****
2024-02-27 10:29:54.355 - INFO 21092 --- [Thread-5] o.cloud.sonic.agent.bridge.ios.SibTool   : 2024-02-27 10:29:55.554572+0800 WebDriverAgentRunner-Runner[655:19406] [Default] Running tests...
2024-02-27 10:29:54.397 - INFO 21092 --- [Thread-5] o.cloud.sonic.agent.bridge.ios.SibTool   : 2024-02-27 10:29:55.596586+0800 WebDriverAgentRunner-Runner[655:19406] [Default] **Error while preparing for testing: (null)**
2024-02-27 10:30:52.928 - INFO 21092 --- [http-nio-7777-exec-1] o.cloud.sonic.agent.bridge.ios.SibTool   : **** WebDriverAgent start timeout!
cn.hutool.core.io.IORuntimeException: BindException: Cannot assign requested address: connect
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1272)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1137)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1013)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:989)
	at org.cloud.sonic.driver.common.tool.RespHandler.getResp(RespHandler.java:45)
	at org.cloud.sonic.driver.common.tool.RespHandler.getResp(RespHandler.java:39)
	at org.cloud.sonic.driver.ios.service.impl.WdaClientImpl.newSession(WdaClientImpl.java:126)
	at org.cloud.sonic.driver.ios.IOSDriver.<init>(IOSDriver.java:84)
	at org.cloud.sonic.driver.ios.IOSDriver.<init>(IOSDriver.java:58)
	at org.cloud.sonic.driver.ios.IOSDriver.<init>(IOSDriver.java:47)
	at org.cloud.sonic.agent.tests.handlers.IOSStepHandler.startIOSDriver(IOSStepHandler.java:121)
	at org.cloud.sonic.agent.websockets.IOSWSServer.lambda$onOpen$1(IOSWSServer.java:141)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.BindException: Cannot assign requested address: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:385)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:407)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
	at cn.hutool.http.HttpConnection.getOutputStream(HttpConnection.java:449)
	at cn.hutool.http.HttpRequest.sendFormUrlEncoded(HttpRequest.java:1295)
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1264)
	... 14 more

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
v2.6.4已修复，请更新版本

**Comment by chenshuai12** [comment]
升级后可以启动wda了，但是通过云真机点击或者滑动屏幕时，报错
[sonic-driver-core] 2024-02-27 13:42:22 [ERROR] perform failed.
org.cloud.sonic.driver.common.tool.SonicRespException: Unhandled endpoint: /session/C6D0B86F-0D59-4D0E-AAE2-1D0BF4D761E5/wda/touch/multi/perform -- http://127.0.0.1:56386/ with parameters {
    wildcards =     (
        "session/C6D0B86F-0D59-4D0E-AAE2-1D0BF4D761E5/wda/touch/multi/perform"
    );
}
	at org.cloud.sonic.driver.ios.service.impl.WdaClientImpl.performTouchAction(WdaClientImpl.java:214)
	at org.cloud.sonic.driver.ios.IOSDriver.performTouchAction(IOSDriver.java:233)
	at org.cloud.sonic.driver.ios.IOSDriver.tap(IOSDriver.java:174)
	at org.cloud.sonic.agent.websockets.IOSWSServer.lambda$onMessage$3(IOSWSServer.java:326)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ZhouYixun** [comment]
https://github.com/appium/WebDriverAgent/pull/847

因为wda那边把触控接口调整了，你稍微降一下wda版本就行，我将我们组织仓库的先回退下

**Comment by ZhouYixun** [comment]
https://github.com/SonicCloudOrg/sonic-ios-wda 试下这个

**Comment by chenshuai12** [comment]
换成这个包ios15设备确实可以了，另外我用IOS17设备连接时报另外一个异常， 是暂时还不支持IOS17吗？
2024-02-27 16:49:06.973 - INFO 14824 --- [http-nio-7777-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-02-27 16:49:06.974 - INFO 14824 --- [http-nio-7777-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-02-27 16:49:06.975 - INFO 14824 --- [http-nio-7777-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 0 ms
2024-02-27 16:49:07.005 - INFO 14824 --- [http-nio-7777-exec-1] o.c.sonic.agent.websockets.IOSWSServer   : ios lock udId：
2024-02-27 16:49:07.749 - INFO 14824 --- [Thread-5] o.cloud.sonic.agent.bridge.ios.SibTool   : WebDriverAgent server start failed: receive packet: InvalidService
2024-02-27 16:49:07.750 - INFO 14824 --- [Thread-5] o.cloud.sonic.agent.bridge.ios.SibTool   : WebDriverAgent print thread shutdown.

**Comment by Pycoder0901** [comment]
wda目前应该还不支持iOS17

**Comment by ZhouYixun** [comment]
> wda目前应该还不支持iOS17

wda支持，但是sib暂时不支持，ios17挂载方式改了

**Comment by Pycoder0901** [comment]
> > wda目前应该还不支持iOS17
> 
> wda支持，但是sib暂时不支持，ios17挂载方式改了

大佬牛逼

**Comment by chenshuai12** [comment]
> > wda目前应该还不支持iOS17
> 
> wda支持，但是sib暂时不支持，ios17挂载方式改了

大佬啥时候能支持下sib

**Comment by Pycoder0901** [comment]
> > wda目前应该还不支持iOS17
> 
> wda支持，但是sib暂时不支持，ios17挂载方式改了

那就说明现在iOS17的设备在sonic上都跑不起来对吧

**Comment by Pycoder0901** [comment]
> 换成这个包ios15设备确实可以了，另外我用IOS17设备连接时报另外一个异常， 是暂时还不支持IOS17吗？ 2024-02-27 16:49:06.973 - INFO 14824 --- [http-nio-7777-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/] : Initializing Spring DispatcherServlet 'dispatcherServlet' 2024-02-27 16:49:06.974 - INFO 14824 --- [http-nio-7777-exec-1] o.s.web.servlet.DispatcherServlet : Initializing Servlet 'dispatcherServlet' 2024-02-27 16:49:06.975 - INFO 14824 --- [http-nio-7777-exec-1] o.s.web.servlet.DispatcherServlet : Completed initialization in 0 ms 2024-02-27 16:49:07.005 - INFO 14824 --- [http-nio-7777-exec-1] o.c.sonic.agent.websockets.IOSWSServer : ios lock udId： 2024-02-27 16:49:07.749 - INFO 14824 --- [Thread-5] o.cloud.sonic.agent.bridge.ios.SibTool : WebDriverAgent server start failed: receive packet: InvalidService 2024-02-27 16:49:07.750 - INFO 14824 --- [Thread-5] o.cloud.sonic.agent.bridge.ios.SibTool : WebDriverAgent print thread shutdown.

大佬解决没
