### ISSUE TITLE
[help] IOS手机隔一段时间就会断开连接要怎么办？

### ISSUE THREAD

**Issue by jeniva** [SonicCloudOrg/sonic-agent#430]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.4

### Deploy platform

Linux  java -jar 运行

### Minimal reproduce step

1.接上iphone，刚开始都是在线的
2.隔了几天就全部离线了
3.通过sib devices查看手机都没有了还报错，ps查看usbmuxd服务是在的,但是手机就连不上
![image](https://github.com/SonicCloudOrg/sonic-agent/assets/8514029/39b62a5f-d666-4a99-8408-72a82cda038a)
4.重启agent也没恢复
![image](https://github.com/SonicCloudOrg/sonic-agent/assets/8514029/9cf1be8c-ada2-4470-9e05-383dfee7f067)
5.需要重启systemctl restart usbmuxd并且重启agent才能恢复一部分，还有一部分是开发者模式消失了就上线不了。
现在的问题是怎么让ios可以长时间运行而不需要手动的进行上面的操作呢？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
这个resource的报错还是第一次见到，我后面看看

**Comment by jeniva** [comment]
好的，还有一种情况就是报错后直接都下线了，再也上线不了，sib devices是能查询出来的，但是agent没上报成功，需要重启agent，这个报错有办法解决吗？
![image](https://github.com/SonicCloudOrg/sonic-agent/assets/8514029/8f5927eb-648a-4593-a669-c8fe3e4dcaf2)

**Comment by ZhouYixun** [comment]
这个只能重启agent了，现在还会吗

**Comment by Pycoder0901** [comment]
iOS我这边在跑套件的时候 跑三四十条就会断开连接
org.cloud.sonic.driver.common.tool.SonicRespException: ConnectException: Connection refused
	at org.cloud.sonic.agent.tests.handlers.IOSStepHandler.exceptionLog(IOSStepHandler.java:1116)
	at org.cloud.sonic.agent.tests.handlers.IOSStepHandler.switchType(IOSStepHandler.java:2012)
	at org.cloud.sonic.agent.tests.handlers.IOSStepHandler.runStep(IOSStepHandler.java:1943)
	at org.cloud.sonic.agent.tests.handlers.NoneConditionHandler.runStep(NoneConditionHandler.java:46)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
	at org.cloud.sonic.agent.aspect.IteratorAspect.around(IteratorAspect.java:25)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:173)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at org.cloud.sonic.agent.tests.handlers.NoneConditionHandler$$SpringCGLIB$$0.runStep(<generated>)
	at org.cloud.sonic.agent.tests.handlers.StepHandlers.runStep(StepHandlers.java:42)
	at org.cloud.sonic.agent.tests.ios.IOSRunStepThread.run(IOSRunStepThread.java:95)

**Comment by Pycoder0901** [comment]
手机还是连接电脑ok的状态 但是WDA断开了 sonic平台没设备了 
<img width="354" alt="image" src="https://github.com/user-attachments/assets/0cd904f7-c6c2-4c86-afba-921a94070e7e">

**Comment by ZhouYixun** [comment]
> 手机还是连接电脑ok的状态 但是WDA断开了 sonic平台没设备了 <img alt="image" width="354" src="https://private-user-images.githubusercontent.com/76036836/387674303-0cd904f7-c6c2-4c86-afba-921a94070e7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzAxOTMsIm5iZiI6MTczMjA2OTg5MywicGF0aCI6Ii83NjAzNjgzNi8zODc2NzQzMDMtMGNkOTA0ZjctYzZjMi00Yzg2LWFmYmEtOTIxYTk0MDcwZTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMzEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYTVkODFmNjIxYjE5NTA0MTMwYjdlMmRiNzJiOTcwZmJkZTg5NGM0OTM3Zjc0OTQ1MjVlODNlZmFlMjc0OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8KpPWRfPYfeVR5DtKx9A5yl9bmfDOwWMFHEIftIYPuc">

顺便说下，tidevice有可能会和sib冲突
