### ISSUE TITLE
[Bug] iOS运行套件几十条之后 手机拒绝链接。

### ISSUE THREAD

**Issue by Pycoder0901** [SonicCloudOrg/sonic-agent#475]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

最新版

### Deploy platform

macOS

### Minimal reproduce step

cn.hutool.core.io.IORuntimeException: ConnectException: Connection refused
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1272)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1137)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1013)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:989)
	at org.cloud.sonic.driver.common.tool.RespHandler.getResp(RespHandler.java:45)
	at org.cloud.sonic.driver.common.tool.RespHandler.getResp(RespHandler.java:39)
	at org.cloud.sonic.driver.ios.service.impl.WdaClientImpl.appActivate(WdaClientImpl.java:338)
	at org.cloud.sonic.driver.ios.IOSDriver.appActivate(IOSDriver.java:369)
	at org.cloud.sonic.agent.tests.handlers.IOSStepHandler.openApp(IOSStepHandler.java:427)
	at org.cloud.sonic.agent.tests.handlers.IOSStepHandler.openScheme(IOSStepHandler.java:2140)
	at org.cloud.sonic.agent.tests.handlers.IOSStepHandler.loginApp(IOSStepHandler.java:2047)
	at org.cloud.sonic.agent.tests.handlers.IOSStepHandler.runStep(IOSStepHandler.java:1910)
	at org.cloud.sonic.agent.tests.handlers.NoneConditionHandler.runStep(NoneConditionHandler.java:46)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
	at org.cloud.sonic.agent.aspect.IteratorAspect.around(IteratorAspect.java:25)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:173)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at org.cloud.sonic.agent.tests.handlers.NoneConditionHandler$$SpringCGLIB$$0.runStep(<generated>)
	at org.cloud.sonic.agent.tests.handlers.StepHandlers.runStep(StepHandlers.java:42)
	at org.cloud.sonic.agent.tests.ios.IOSRunStepThread.run(IOSRunStepThread.java:95)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:554)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:281)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
	at cn.hutool.http.HttpConnection.getOutputStream(HttpConnection.java:449)
	at cn.hutool.http.HttpRequest.sendFormUrlEncoded(HttpRequest.java:1295)
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1264)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
连不上手机了，重启手机试试吧

**Comment by Pycoder0901** [comment]
> 连不上手机了，重启手机试试吧

重启了也没用 能重启的都重启了 套件有一百多条case 每次都是30条左右的时候断联 只有iOS会这样 更换手机也未解决 期待有人遇到一样的问题

**Comment by ZhouYixun** [comment]
你30个ios在同一个电脑？

**Comment by Pycoder0901** [comment]
> 你30个ios在同一个电脑？

不是啊 就一台手机一台电脑 是一百条运行到三十条的时候失败

**Comment by ZhouYixun** [comment]
> > 你30个ios在同一个电脑？
> 
> 不是啊 就一台手机一台电脑 是一百条运行到三十条的时候失败

不应该啊，我每个case前后会销毁driver的，你是不是第三十多条运行太久？

**Comment by Pycoder0901** [comment]
> > > 你30个ios在同一个电脑？
> > 
> > 
> > 不是啊 就一台手机一台电脑 是一百条运行到三十条的时候失败
> 
> 不应该啊，我每个case前后会销毁driver的，你是不是第三十多条运行太久？

每个case不到3分钟 加起来也就一个多小时 就会失败

**Comment by ZhouYixun** [comment]
https://github.com/SonicCloudOrg/sonic-agent/blob/main/src/main/java/org/cloud/sonic/agent/tests/ios/IOSTestTaskBootThread.java#L218

**Comment by Pycoder0901** [comment]
> https://github.com/SonicCloudOrg/sonic-agent/blob/main/src/main/java/org/cloud/sonic/agent/tests/ios/IOSTestTaskBootThread.java#L218

确实有人把代码给删了。。。感谢大佬
